name: Lint
on:
  push:
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # We cache the elements of the Cabal store separately, as the entirety of ~/.cabal can grow very large for projects with many dependencies.
      - uses: actions/cache@v1
        name: Cache ~/.cabal/packages
        with:
          path: ~/.cabal/packages
          key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-packages

      - uses: actions/cache@v1
        name: Cache ~/.cabal/store
        with:
          path: ~/.cabal/store
          key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-store

      - uses: actions/cache@v1
        name: Cache dist-newstyle
        with:
          path: dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-dist-newstyle
      ################################################################

      - uses: actions/checkout@v1

      - uses: actions/setup-haskell@v1
        with:
          ghc-version: "8.6.5"
          cabal-version: "3.0"

      - name: Run HLint
        run: |
          curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s ./app ./benchmark ./src ./test
